
name: develop-website

on: 
 push: 
   branches: ['main']
 workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  
      - uses: actions/checkout@v2
      - name: install nodejs
        uses: actions/setup-node@v4.0.3
        with: 
          node-version: '14.x'
      - name: install deps
        run: npm install
      - name: build app
        run: npm run build
      - name: copy dist file with scp
        uses: appleboy/scp-action@v0.0.1
        with: 
         host: ''
         username: ''
         password: ''
         post: 22
         source: 'dist/'
         target: ''

         



      
